---
title: "MCA"
author: "Thomas Klebel"
date: "11/4/2019"
output: html_document
---

```{r}
library(drake)
library(ca)

loadd(data)
loadd(labels)
```


```{r, fig.width=10, fig.height=10}
data %>% 
  select(DHRP03b_SQ003_, contains("DHRP06")) %>% 
  mutate(id = seq_along(DHRP03b_SQ003_)) %>% 
  tidyr::gather(var, val, -id) %>% 
  left_join(labels, by = "var") %>% 
  mutate(val_new = paste(label, "_", val)) %>% 
  select(id, var, val_new) %>%
  pivot_wider(names_from = var, values_from = val_new) %>% 
  select(-id) %>% 
  ca::mjca() %>% 
  plot_ca()
```


Dimension 1 opposes those that are missing and those that are not. Therefore we
remove the missings, since this doesnt give us new insights. We further remove
those that chose "dont know/cannot answer", since they are a similar group too.

```{r, fig.width=14, fig.height=10}
data %>% 
  select(DHRP03b_SQ003_, contains("DHRP06"), D06) %>% 
  mutate(id = seq_along(DHRP03b_SQ003_)) %>% 
  tidyr::gather(var, val, -id, -D06) %>% 
  left_join(labels, by = "var") %>% 
  mutate(val_new = paste(label, "_", val),
         val_new = str_replace(val_new, "...sharing research data", "sharing")) %>% 
  select(id, var, val_new, D06) %>% 
  pivot_wider(names_from = var, values_from = val_new) %>% 
  select(-id) %>% 
  filter_all(all_vars(!str_detect(., "NA|answer"))) %>% 
  select(starts_with("DHR"), D06) %>% 
  ca::mjca(supcol = 6) %>% 
  plot_ca(lines = TRUE) 
```
